GoogleForms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('forms.urls')),
]

forms/urls.py
from django.urls import path
from . import views

app_name = 'forms'

urlpatterns = [
    path('', views.home, name='home'),
    path('create',views.create, name='create'),
    path('forms/<str:pk>/edit',views.update_forms, name='update_forms'),
    path('forms/<str:pk>/viewForm',views.get_user_response, name='view_form'),
    path('forms/<str:pk>/responses',views.response, name='responses'),
]

forms/models.py
from django.db import models

# Create your models here.

forms/admin.py
from django.contrib import admin

# Register your models here.

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "forms"

forms/tests.py
from django.test import TestCase

# Create your tests here.

forms/utils.py
import pymongo
from django.utils import timezone
from bson import ObjectId

client = pymongo.MongoClient("mongodb://localhost:27017/")
db = client['GoogleForms']
col = db['GoogleForms']

class Form:
    def create(self):
        obj = col.insert_one({
            'created': timezone.now()
        })
        return str(obj.inserted_id)
    
    def find(self,pk):
        query = {
            '_id':ObjectId(pk)
        }
        return col.find(query).next()

    def update(self,pk,form_data):
        query = {'_id':ObjectId(pk)}
        updated_value = { 
            '$set': {
                'form_data':form_data['formData'],
                'updated_time': timezone.now()
            }
        }
        col.update_one(query, updated_value)

    def findall(self):
        return col.find().sort('updated', -1)

    def update_response(self, pk, response):
        query = {'_id':ObjectId(pk)}
        update_value = { 
            '$inc': response
        }
        col.update_one(query, update_value)

forms/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.http import Http404, JsonResponse
from .utils import Form
import json

# Create your views here.
Form = Form()

def get_uuid():
    return 'user'

def home(request):
    forms = Form.findall()
    return render(request, 'home.html', {
        'forms':forms
    })

def create(request):
    pk = Form.create()
    return HttpResponseRedirect(reverse_lazy('forms:update_forms', args=[pk]))

def update_forms(request, pk):
    if request.method == 'POST':
        form_data = json.loads(request.body)
        Form.update(pk, form_data)
        return JsonResponse ({
            'saved':'ok'
        })
    try:
        form_data = Form.find(pk)
        return render(request, 'update.html',{
            'pk':pk,
            'form':form_data
        })
    except Exception as e:
        print(e)
        raise Http404('Form not found')

def get_user_response(request, pk):
    if request.method == 'POST':
        cd = dict(request.POST)
        del cd['csrfmiddlewaretoken']
        response = {}
        for key, value in cd.items():
            print(key,value[0])
            response.update({
                f"response.{key}.{value[0]}":1
            })
        Form.update_response(pk, response)
        return render(request, 'thankyou.html')
    else:
        try:
            form_data = Form.find(pk)
            return render(request, "get_response.html", {
                'pk':pk,
                'form':form_data
            })
        except: 
            raise Http404("Form Not Found")

def response(request, pk):
    form_data = Form.find(pk)
    return render(request, "responses.html", {
            # 'pk':pk,
            'form':form_data
        })

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>
    {% block content %}{% endblock content %}
</body>

{% block script %}{% endblock script %}

</html>

templates/get_response.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{form.form_data.title}}</h5>
        <p class="card-text">{{form.form_data.description}}</p>
    </div>
</div>

<form action="{% url 'forms:view_form' pk %}" method='POST'>

    {% csrf_token %}

    {% with form.form_data.data as questions %}
    
    {% for questionId, questionData in questions.items %}
    
        <div class="card mt-2">
            <div class="class-header fw-bold">
                Question{{forloop.counter}}
            </div>
            <div class="card-body">
                <div class="form-floating mb-2">
                    <p id="{{questionId}}" class="font-monospace fs-5">{{questionData.questionText}}</p>
                </div>
            </div>
            {% for option in questionData.options %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" id="{{questionId}}-{{forloop.counter}}" name="{{questionId}}" value={{option}}>
                    <label class="form-check-label" for="{{questionId}}-{{forloop.counter}}">
                        {{option}}
                    </label>
                </div>
            {% endfor %}  
        </div>

    {% endfor %}
    
    {% endwith %}
    <input type="Submit" value="Submit" class='mt-2'>

</form>

{% endblock content %}

templates/home.html
{% load form_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Form Base</h1>
    <a href="{%url 'forms:create'%}"><button>Create Form</button></a>

    <table>
        <tr>
            <th>Title</th>
            <th>Updated On</th>
            <th>Created On</th>
            <th>View</th>
        </tr>

        {% for form in forms %}
            {% if form.updated_time %}
            <tr>
                <td>{{form.form_data.title}}</td>
                <td>{{form.updated_time}}</td>
                <td>{{form.created}}</td>
                <td><a href="{% url 'forms:update_forms' form|lookup:"_id" %}" target="_blank">Open in new browser</a></td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
</body>
</html>

templates/responses.html
{% extends 'base.html' %}
{% load form_filters %}

{% block content %} 

    <h1>Responses</h1>
    {% with form.form_data as forms %}
    
        {% with forms.data as data %}

        {% for questionID, responses in form.response.items %}
        
        <div class="card">
            <div class="card-header font-monospace fw-bold">
                {% with data|lookup:questionID as question %} Q{{forloop.counter}}. {{question.questionText}} {% endwith %}
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Option</th>
                            <th scope="col">Response</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for response, count in responses.items %}
                        <tr>
                            <td>{{response}}</td>
                            <td>{{count}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
        {% endfor %}
        
        {% endwith %}

    {% endwith %}

{% endblock %}

templates/thankyou.html
{% extends 'base.html' %}

{% block content %}
    <center><h1>Thank you, your resposnse have been saved.</h1></center>
{% endblock content %}

templates/update.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>Update Form</h1>

<a href="{% url 'forms:view_form' pk %}" target="_blank"><button>Share</button></a><br><br>
<a href="{% url 'forms:responses' pk %}" target="_blank"><button>Responses</button></a><br><br>


<form action="{% url 'forms:update_forms' pk %}" method="post" id='questionForm'>
    {% csrf_token %}
    <Button type='submit'>Save</Button><br><br>

    <div class="card" id='form-description'>
        <div class="card-header">
            Title and Description
        </div>
        <div class="card-body">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="title" placeholder="title" name='title' >
                <label for="title">Form Title</label>
            </div>
            <div class="form-floating">
                <textarea class="form-control" placeholder="Description" id="description"
                    name='description'></textarea>
                <label for="description">Form Description</label>
            </div>
        </div>
        <button type='button' id='addQuestion'>Add Question</button>
    </div>
</form>


{% endblock content %}

{% block script %}
<script src="{% static 'forms.js' %}"> </script>

<script>
    
    let children = form.children
    children[2].querySelector('[name=title]').value = "{{form.form_data.title|escapejs}}"
    children[2].querySelector('[name=description]').value = "{{form.form_data.description|escapejs}}"

    {% if form.form_data.data %}

        let addQuestionButtonId = 'addQuestion';
        let addOptionButtonId, question, option_id;
        let i = 0;
    
        {% with form.form_data.data as questions %}

            {% for questionId, questionData in questions.items %}

                i = {{forloop.counter0|escapejs}}+3;
                [addQuestionButtonId, addOptionButtonId] = addQuestion(addQuestionButtonId, false);

                children[i].querySelector('.question').value = "{{questionData.questionText|escapejs}}";

                {% for option in questionData.options %}
                    option_id = addOption(addOptionButtonId);
                    allopt = children[i].querySelector('.allOptions').children;
                    allopt[allopt.length-1].querySelector(`#${option_id}`).value = '{{option}}';
                {% endfor %}

            {% endfor %}
        {% endwith %}

    {% endif %}

</script>

{% endblock script %}